---
- name: Update and upgrade software packages
  hosts: all
  become: yes
  tasks:
  - name: Update packages with apt
    apt:
      update_cache: yes
    when: ansible_pkg_mgr == "apt"

  - name: Upgrade packages with apt
    apt:
      upgrade: dist
    when: ansible_pkg_mgr == "apt"

  - name: Update all apps with apt
    apt:
      name: "*"
      state: latest
    when: ansible_pkg_mgr == "apt"

  - name: Update packages with dnf
    dnf:
      update_cache: yes
    when: ansible_pkg_mgr == "dnf"

  - name: Update all apps with dnf
    dnf:
      name: "*"
      state: latest
    when: ansible_pkg_mgr == "dnf"
